# Generated by Django 4.2.2 on 2025-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="link",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="session_id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                default="cash",
                max_length=10,
                verbose_name="Вариант оплаты",
            ),
        ),
    ]
