# Generated by Django 4.2.2 on 2025-08-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_payment_link_remove_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите на оплату товара",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату товара",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Введите Id сессии",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
    ]
