# Generated by Django 4.2.2 on 2025-07-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="owner",
        ),
    ]
