# Generated by Django 4.2.2 on 2025-08-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0005_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="sign_of_subscription",
            field=models.BooleanField(default=False, verbose_name="Характер подписки"),
        ),
    ]
